version: '3.7'
services:
  unifi-db:
    image: docker.io/mongo:6.0
    container_name: unifi-db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD='A~TC#3+T!*k9TX#
    volumes:
        - ./data:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - MONGO_USER=unifi
        - MONGO_PASS=E+;oL6$H1<E4|HD1
        - MONGO_HOST=unifi-db
        - MONGO_PORT=27017
        - MONGO_DBNAME=unifi
    volumes:
        - ./config:/config
    ports:
        - 8443:8443
        - 3478:3478/udp
        - 10001:10001/udp
        - 8080:8080
    restart: unless-stopped

    restart: unless-stopped
