version: "3.7"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
       - NET_ADMIN
    devices:
       - /dev/net/tun
    restart: unless-stopped
    dns:
       - 8.8.8.8
       - 8.8.4.4
    volumes:
       - /mnt/harddisk3/downloads:/data
       - "${APP_DATA_DIR}/transmission-openvpn:/config"
       - "${APP_DATA_DIR}/transmission/cyberghost-openvpn:/etc/openvpn/custom"
    environment:
#       - TRANSMISSION_WEB_UI=kettu
       - OPENVPN_PROVIDER=CUSTOM
       - OPENVPN_CONFIG=cyberghost
       - OPENVPN_USERNAME=uTxMB6pkhq
       - OPENVPN_PASSWORD=YUzqmjKKmd
       - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
       - LOCAL_NETWORK=192.168.1.0/24
       - PUID=1000
       - PGID=100
    ports:
       - '9092:9091'
       - '8888:8888'